In [1]:
import torch
import numpy as np

In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
  x_ones = torch.ones_like(x_data)
  print(f"ones tensors: \n {x_ones} \n")
  x_rands = torch.rand_like(x_data, dtype=torch.float)
  print(f"random tensors: \n {x_rands} \n ")

ones tensors: 
 tensor([[1, 1],
        [1, 1]]) 

random tensors: 
 tensor([[0.2169, 0.0324],
        [0.1922, 0.6749]]) 
 


In [15]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4071, 0.2081, 0.6235],
        [0.6968, 0.7063, 0.4203]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [4]:
if torch.accelerator.is_available():
  tensor =  tensor.to(torch.accelerator.current_accelerator())

In [6]:
tensors = torch.ones(4,4)
print(f"first row: {tensors[0]}")
print(f"first column: {tensors[:,0]}")
print(f"last column: {tensors[...,-1]}")
tensors[:,1] = 0
print(tensors)

first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [7]:
t1 = torch.cat([tensor,tensor,tensor], dim = 1)
print(t1)

tensor([[0.8629, 0.0130, 0.9955, 0.1034, 0.8629, 0.0130, 0.9955, 0.1034, 0.8629,
         0.0130, 0.9955, 0.1034],
        [0.3779, 0.1377, 0.2909, 0.7110, 0.3779, 0.1377, 0.2909, 0.7110, 0.3779,
         0.1377, 0.2909, 0.7110],
        [0.8635, 0.7616, 0.2533, 0.4150, 0.8635, 0.7616, 0.2533, 0.4150, 0.8635,
         0.7616, 0.2533, 0.4150]], device='cuda:0')
